# Generated by Django 3.0.7 on 2021-02-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('address', models.CharField(max_length=250, verbose_name='адрес')),
                ('products', models.ManyToManyField(related_name='orders', to='foodcartapp.Product', verbose_name='продукты')),
            ],
        ),
    ]
