# Generated by Django 3.0.7 on 2021-02-11 18:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20210211_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79169053303', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
