# Generated by Django 3.0.7 on 2021-03-27 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('foodcartapp', '0046_order_shirt_size'), ('foodcartapp', '0047_auto_20210220_2042'), ('foodcartapp', '0048_auto_20210220_2048'), ('foodcartapp', '0049_auto_20210220_2049'), ('foodcartapp', '0050_auto_20210220_2050'), ('foodcartapp', '0051_auto_20210224_2049'), ('foodcartapp', '0052_auto_20210224_2052'), ('foodcartapp', '0053_auto_20210224_2053'), ('foodcartapp', '0054_auto_20210224_2055'), ('foodcartapp', '0055_order_payment'), ('foodcartapp', '0056_order_restaurant'), ('foodcartapp', '0057_auto_20210304_2106')]

    dependencies = [
        ('foodcartapp', '0045_auto_20210218_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'Новый'), ('preparation', 'Готовится'), ('in_delivery', 'У курьера'), ('finished', 'Доставлен')], default='new', max_length=15, verbose_name='статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='called',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Картой на сайте')], default='', max_length=15, verbose_name='способ оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.Restaurant', verbose_name='ресторан'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.Order', verbose_name='заказ'),
        ),
    ]
