# Generated by Django 3.0.7 on 2021-02-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20210218_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shirt_size',
            field=models.CharField(choices=[('new', 'Новый'), ('preparation', 'Готовится'), ('in_delivery', 'У курьера'), ('finished', 'Доставлен')], default='new', max_length=15),
        ),
    ]
