# Generated by Django 3.0.7 on 2021-02-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_shirt_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shirt_size',
            new_name='order_status',
        ),
    ]
