# Generated by Django 3.0.7 on 2021-02-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20210220_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'Новый'), ('preparation', 'Готовится'), ('in_delivery', 'У курьера'), ('finished', 'Доставлен')], default='new', max_length=15, verbose_name='статус заказа'),
        ),
    ]
