# Generated by Django 3.0.7 on 2021-02-24 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20210220_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время звонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время доставки'),
            preserve_default=False,
        ),
    ]
