# Generated by Django 3.0.7 on 2021-02-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20210224_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Картой на сайте')], default='', max_length=15, verbose_name='способ оплаты'),
            preserve_default=False,
        ),
    ]
